services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
